### ISSUE TITLE
Tag Reference is not in repository

### ISSUE THREAD

**Issue by NerdyNathan** [Sagelt/Dungeon-World#196]
My published copy of Dungeon World contains a Tag Reference section that is not found in this repository. Is that intentional?

**Comment by Sagelt** [comment]
Yes, the print book includes a few useful things for reference, as well as an index and backer credits, which aren't included in the raw text. The actual tags are all described in [the raw text](https://github.com/Sagelt/Dungeon-World/blob/master/text/Equipment.xml), there's just not an additional reference since when working with digital text there's no need for a second copy just for reference.
